theme = "PaperMod"
baseURL = 'https://milav.in/'
defaultContentLanguage = "en"

# Enable features

enableEmoji = true
enableRobotsTXT = true
enableGitInfo = false
enableInlineShortcodes = true

buildDrafts = false
buildFuture = false
buildExpired = false

copyright = "Milav Dabgar"
pygmentsUseClasses = true
summaryLength = 30
hasCJKLanguage = false

mainsections = ["blog", "resource"]

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'always'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[services]
  [services.instagram]
    disableInlineCSS = true
  # Removing twitter service as it's deprecated

[minify]
  disableXML = true
  # minifyOutput = true