languageName = "ркЧрлБркЬрк░рк╛ркдрлА"
weight = 2
title = "ркорк┐рк▓рк╡"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[params]
  [params.profileMode]
    enabled = true
    title = "ркорк┐рк▓рк╡ ркбркмркЧрк░"
    subtitle = "тШДя╕П ркЭркбрккрлА | тШБя╕П рк╕рк░рк│ | ЁЯМЩ рк╕рлБркВркжрк░ | ЁЯУ▒ рк░рк┐рк╕рлНрккрлЛркирлНрк╕рк┐рк╡"
    imageUrl = "https://raw.githubusercontent.com/googlefonts/noto-emoji/master/svg/emoji_u1f9d1_1f3fb_200d_1f4bb.svg"
    imageTitle = "ркорк┐рк▓рк╡ ркбркмркЧрк░"
    
    [[params.profileMode.buttons]]
      name = "ркмрлНрк▓рлЛркЧ"
      url = "posts"
    [[params.profileMode.buttons]]
      name = "ркЖрк░рлНркХрк╛ркЗрк╡"
      url = "archives"

  [params.editPost]
    Text = "рклрлЗрк░рклрк╛рк░ рк╕рлВркЪрк╡рлЛ"
  
  ReadMore = "рк╡ркзрлБ рк╡рк╛ркВркЪрлЛ"
  PostNavigation = "рккрлЛрк╕рлНркЯ ркирлЗрк╡рк┐ркЧрлЗрк╢рки"
  PrevPage = "рккрк╛ркЫрк│"
  NextPage = "ркЖркЧрк│"
  ShowReadingTime = true
  DateFormat = "2006, January 2"
  ShowShareButtons = true
  ShareButtons = ["facebook", "twitter", "telegram", "whatsapp"]
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  searchText = "ркЕрк╣рлАркВ рк╢рлЛркзрлЛ..."
  poweredBy = "ркжрлНрк╡рк╛рк░рк╛ рк╕ркВркЪрк╛рк▓рк┐ркд"
  lastMod = "ркЫрлЗрк▓рлНрк▓рлЗ рк╕рлБркзрк╛рк░рк╛ркпрлБркВ"
  readTime = "рк╡рк╛ркВркЪрк╡рк╛ркирлЛ рк╕ркоркп"
  words = "рк╢ркмрлНркжрлЛ"
  draft = "ркбрлНрк░рк╛рклрлНркЯ"
  toc = "ркЕркирлБркХрлНрк░ркоркгрк┐ркХрк╛"