languageCode = "gu"
languageName = "ркЧрлБркЬрк░рк╛ркдрлА"
weight = 2
title = "ркорк┐рк▓рк╡"

[params]
  displayName = "ркЧрлБркЬрк░рк╛ркдрлА"
  isoCode = "gu"
  description = "ркорк┐рк▓рк╡ ркбркмркЧрк░ ркжрлНрк╡рк╛рк░рк╛ рк╡рлНркпркХрлНркдрк┐ркЧркд ркмрлНрк▓рлЛркЧ ркЕркирлЗ ркЕркнрлНркпрк╛рк╕ рк╕рк╛ркоркЧрлНрк░рлА"
  author = "ркорк┐рк▓рк╡ ркбркмркЧрк░"

  [params.profileMode]
    enabled = true
    title = "ркорк┐рк▓рк╡ ркбркмркЧрк░"
    subtitle = "тШДя╕П ркЭркбрккрлА | тШБя╕П рк╕рк░рк│ | ЁЯМЩ рк╕рлБркВркжрк░ | ЁЯУ▒ рк░рк┐рк╕рлНрккрлЛркирлНрк╕рк┐рк╡"
    imageUrl = "img/milav-avtar.jpeg"
    imageTitle = "ркорк┐рк▓рк╡ ркбркмркЧрк░"
    
    [[params.profileMode.buttons]]
      name = "ркмрлНрк▓рлЛркЧ"
      url = "blog"
    [[params.profileMode.buttons]]
      name = "ркЖрк░рлНркХрк╛ркЗрк╡"
      url = "archives"