baseURL: "https://milav.in"
title: Milav Dabgar
languageCode: en-us
theme: PaperMod

# Enable features
enableEmoji: true
enableRobotsTXT: true
enableGitInfo: false

# Basic settings
pagination:
  pagerSize: 10
summaryLength: 30

# Taxonomy settings
taxonomies:
  category: categories
  tag: tags
  series: series

# Content organization
params:
  subtitle: "Lecturer, Dept. of ECE, GPP | Tech Enthusiast"
  github: "https://github.com/milavdabgar"
  linkedin: "https://linkedin.com/in/milavdabgar"
  email: "milav.dabgar@gujgov.edu.in"

  math: true
  
  mainSections:
    - posts
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  
  # Category descriptions
  categoryDescriptions:
    programming: "Programming tutorials, code examples, and implementation guides"
    linux: "Linux installation, configuration, and system setup guides"
    tutorials: "General tutorials and how-to guides"
    data-science: "Data science, machine learning, and deep learning articles"
    raspberry-pi: "Raspberry Pi projects and tutorials"

# Menu configuration
menu:
  main:
    - name: Home
      url: /
      weight: 10
    - name: Blog
      url: /categories/
      weight: 20
    - name: About
      url: /about/
      weight: 30
    - name: Portfolio
      url: /portfolio/
      weight: 40
    - name: Music
      url: /music/
      weight: 50
    - name: Yoga
      url: /yoga/
      weight: 60
    - name: Downloads
      url: /downloads/
      weight: 70
    - name: Web Links
      url: /weblinks/
      weight: 80
    - name: Quotes
      url: /quotes/
      weight: 90
    - name: Search
      url: /search/
      weight: 100

# Markdown settings
markup:
  goldmark:
    renderer:
      unsafe: true

# Theme parameters
params:
  # Site settings
  env: production
  description: "Milav Dabgar's Personal Website - Portfolio and Blog"
  author: Milav Dabgar
  defaultTheme: auto
  
  # Display settings
  ShowReadingTime: true
  ShowWordCount: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  hidemeta: false
  hideSummary: false
  
  # Home page settings
  profileMode:
    enabled: true
    title: "Milav Dabgar"
    subtitle: "Lecturer, Dept. of ECE, GPP | Tech Enthusiast"
    imageUrl: "/images/profile.jpg"
    imageTitle: "Milav Dabgar"
    imageWidth: 120
    imageHeight: 120
  
  # Social icons
  socialIcons:
    - name: github
      url: "https://github.com/milavdabgar"
    - name: linkedin
      url: "https://www.linkedin.com/in/milavdabgar"
    - name: email
      url: "mailto:milav@milav.in"
