services:
  website:
    build: .
    container_name: milav-hugo
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - npm-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.milav.rule=Host(`milav.in`)"

networks:
  npm-network:
    external: true
