name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace

      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H server.gppalanpur.in >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy
        env:
          REMOTE_HOST: milav@server.gppalanpur.in
          REPO_URL: https://github.com/milavdabgar/milav-hugo.git
        run: |
          ssh $REMOTE_HOST '
            # First, stop any existing containers 
            if [ -f "~/milav-hugo/docker-compose.yml" ]; then
              cd ~/milav-hugo
              docker compose down
            fi
            
            # Now it's safe to remove the directory
            rm -rf ~/milav-hugo
            
            # Clone the repository with submodules in your home directory
            git clone --recursive $REPO_URL ~/milav-hugo
            
            # Navigate to the new directory
            cd ~/milav-hugo
            
            # Build and start the container
            docker compose up -d --build
          '